import Image from "next/image";
import SupportIcon from "../../../public/assets/images/icon.png";
import { demoVideo, levelupFeatures } from "@/constants";
const AboutData = () => {
  return (
    <>
      <section
        id="about"
        className="2xl:max-w-screen-lg mx-auto xl:max-w-screen-lg px-2.5 py-10"
      >
        <h2 className="text-xl text-center mb-6 font-bold uppercase">
          This is <span className="bg-theme px-3 text-white">Levelup</span>
        </h2>
        <div className=" md:text-lg text-base">
          <p className="mb-3">
            <strong>“Level Up”</strong> is a groundbreaking initiative in
            Singapore that leverages AI to revolutionize sports analytics. By
            harnessing the{" "}
            <strong className="underline font-bold ">
              Power of Artificial Intelligence
            </strong>
            , this program aims to enhance the way sports are understood,
            played, and managed. Through advanced data collection and analysis
            techniques, “Level Up” provides coaches, athletes, and teams with
            invaluable insights into their performance, training routines, and
            strategic decisions.
          </p>
          <p className="mb-3">
            The benefits to society are immense. Firstly,
            <strong>AI-powered sports analytics</strong> enable athletes to
            optimize their training regimens, reduce the risk of injuries, and
            improve their overall performance. This contributes to healthier
            athletes and a higher level of competition. Moreover, “Level Up”
            helps coaches make data-driven decisions, leading to more effective
            strategies and better team dynamics.
          </p>
          <p className="mb-3">
            Additionally, the program offers opportunities for talent
            identification and development, potentially uncovering hidden
            talents that might have otherwise gone unnoticed. This promotes
            inclusivity and diversity in sports, creating a more representative
            and equitable athletic community.
          </p>
          <p className="mb-3">
            Furthermore, the insights generated by AI-driven sports analytics
            have the potential to engage and inspire the broader society. Fans
            and spectators gain a deeper understanding of the intricacies of
            different sports, fostering a sense of connection and appreciation
            for athletic achievements. This, in turn, can lead to increased
            interest in physical activity, healthier lifestyles, and a stronger
            sports culture.
          </p>
          <p className="mb-3">
            In summary, the “Level Up” initiative is reshaping the landscape of
            sports analytics in Singapore through AI. Its societal benefits
            encompass improved athlete performance, enhanced coaching
            strategies, increased inclusivity, and a more informed and engaged
            community.
          </p>
        </div>
      </section>
      <section className="2xl:max-w-screen-lg mx-auto xl:max-w-screen-lg px-2.5 py-10">
        <h2 className="text-xl text-center mb-6 font-bold uppercase">
          Checkout our{" "}
          <span className="bg-theme px-3 text-white">Application</span>
        </h2>
        <div className="mt-10 flex gap-5 md:flex-row flex-col">
          <div className="md:w-[60%]">
            <h3 className="md:text-lg text-base font-bold">
              Levelup is your ultimate companion for elevating your cricket
              skills. Whether you are striving to improve your batting, bowling,
              or fielding, this app provides the insights you need to fine-tune
              your game and reach your full potential.
            </h3>

            <h4 className="font-bold md:text-lg text-base mb-2 mt-4">
              LevelUp Provides :
            </h4>
            <ul className="pl-3 mt-3">
              {levelupFeatures.map((each: string) => {
                return (
                  <li
                    key={each}
                    className="flex mb-2 gap-3 md:text-lg text-base"
                  >
                    <Image
                      src={SupportIcon}
                      width={25}
                      height={25}
                      alt="icon"
                      className="object-contain"
                      loading="lazy"
                    />
                    {each}
                  </li>
                );
              })}
            </ul>
          </div>
          <div className="md:ml-auto mx-auto">
            <video width="380" controls>
              <source src={demoVideo} type="video/mp4" />
              <source src={demoVideo} type="video/ogg" />
            </video>
          </div>
        </div>
      </section>
    </>
  );
};

export default AboutData;
